name: pnpm packageManager Update

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    uses: j7an/shared-workflows/.github/workflows/pnpm-packagemanager-update.yml@8aafcda9817cace8993dd7d356457bda549e5f74 # v4.6.0
    with:
      minimum_release_age_days: 5
    secrets: inherit
