name: pnpm packageManager Update

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    uses: j7an/shared-workflows/.github/workflows/pnpm-packagemanager-update.yml@30425ad6ef4ee3c3cbccdd563b22de749887f622 # v4.11.0
    with:
      minimum_release_age_days: 5
    secrets:
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
