name: Security Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  security:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: j7an/shared-workflows/.github/workflows/security-scan.yml@f6fedd5f4a9e33ff83c893abcc608e402c1ee1b0 # v4.10.0
    with:
      run_codeql: false
